PRAGMA journal_mode=DELETE;
BEGIN;
CREATE TABLE [Area] ([OID] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, [Name] nvarchar(100), [OptimisticLockField] int, [GCRecord] int);
CREATE TABLE [AuditDataItemPersistent] ([Oid] char(36) NOT NULL, [UserName] nvarchar(100), [ModifiedOn] datetime, [OperationType] nvarchar(100), [Description] text, [AuditedObject] char(36), [OldObject] char(36), [NewObject] char(36), [OldValue] text, [NewValue] text, [PropertyName] nvarchar(100), [UserId] nvarchar(100), [OptimisticLockField] int, [GCRecord] int, primary key ([Oid]));
CREATE TABLE [AuditedObjectWeakReference] ([Oid] char(36) NOT NULL, [GuidId] char(36), [IntId] int, [DisplayName] nvarchar(250), primary key ([Oid]));
CREATE TABLE [Company] ([OID] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, [Name] nvarchar(100), [OptimisticLockField] int, [GCRecord] int);
CREATE TABLE [Contact] ([Oid] char(36) NOT NULL, [Title] nvarchar(100), [Company] int, [PropertyName] double, primary key ([Oid]));
CREATE TABLE [ControlSystem] ([OID] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, [Name] nvarchar(100), [Type] int, [Description] nvarchar(100), [OptimisticLockField] int, [GCRecord] int);
CREATE TABLE [ControlSystemType] ([OID] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, [Name] nvarchar(100), [Description] nvarchar(100), [OptimisticLockField] int, [GCRecord] int);
CREATE TABLE [DailySchedule] ([OID] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, [AssignedTo] char(36), [Date] datetime, [ScheduledLoop] int, [OptimisticLockField] int, [GCRecord] int);
CREATE TABLE [Drawing] ([OID] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, [File] char(36), [Number] nvarchar(100), [Description] nvarchar(100), [OptimisticLockField] int, [GCRecord] int, [ObjectType] int);
CREATE TABLE [Event] ([Oid] char(36) NOT NULL, [ResourceIds] text, [RecurrencePattern] char(36), [Subject] nvarchar(250), [Description] text, [StartOn] datetime, [EndOn] datetime, [AllDay] bit, [Location] nvarchar(100), [Label] int, [Status] int, [Type] int, [RemindIn] double, [ReminderInfoXml] nvarchar(200), [AlarmTime] datetime, [IsPostponed] bit, [RecurrenceInfoXml] text, [OptimisticLockField] int, [GCRecord] int, [ObjectType] int, [Item] int, [Schedule] char(36), [CheckDate] datetime, primary key ([Oid]));
CREATE TABLE [FileData] ([Oid] char(36) NOT NULL, [size] int, [FileName] nvarchar(260), [Content] image, [OptimisticLockField] int, [GCRecord] int, primary key ([Oid]));
CREATE TABLE [FileLinkObject] ([Oid] char(36) NOT NULL, [FileName] nvarchar(260), [FullName] text, [FileExists] bit, [OptimisticLockField] int, [GCRecord] int, primary key ([Oid]));
CREATE TABLE [IOType] ([OID] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, [Name] nvarchar(100), [Description] nvarchar(100), [OptimisticLockField] int, [GCRecord] int);
CREATE TABLE [Instrument] ([OID] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, [DataSheet] char(36), [TagNumber] nvarchar(100), [PID] int, [JunctionBox] int, [LocationPlan] int, [Calibration] nvarchar(100), [IOType] int, [Loop] int, [LoopDrawing] int, [ControlSystem] int, [InstrumentType] int, [ServiceDescription] nvarchar(100), [ResponsibleCompany] int, [OptimisticLockField] int, [GCRecord] int);
CREATE TABLE [InstrumentType] ([OID] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, [Name] nvarchar(100), [OptimisticLockField] int, [GCRecord] int);
CREATE TABLE [JobInfo] ([OID] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, [Number] nvarchar(100), [Description] nvarchar(100), [ClientName] nvarchar(100), [ClientJobNumber] nvarchar(100), [OptimisticLockField] int, [GCRecord] int);
CREATE TABLE [JunctionBox] ([OID] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, [Number] nvarchar(100), [OptimisticLockField] int, [GCRecord] int);
CREATE TABLE [LocationPlan] ([OID] int NOT NULL, primary key ([OID]));
CREATE TABLE [Loop] ([OID] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, [LoopNumber] nvarchar(100), [Description] nvarchar(100), [LoopCheckStatus] int, [TargetLoopCheckDate] datetime, [LoopFolderReceived] bit, [LoopProvider] int, [OptimisticLockField] int, [GCRecord] int);
CREATE TABLE [LoopCheck] ([Oid] char(36) NOT NULL, [EndOn] datetime, [StartOn] datetime, [OptimisticLockField] int, [GCRecord] int, primary key ([Oid]));
CREATE TABLE [LoopCheckStatus] ([OID] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, [Description] nvarchar(100), [SortOrder] smallint, [OptimisticLockField] int, [GCRecord] int);
CREATE TABLE [LoopDrawing] ([OID] int NOT NULL, primary key ([OID]));
CREATE TABLE [LoopLoops_AreaAreas] ([Areas] int, [Loops] int, [OID] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, [OptimisticLockField] int);
CREATE TABLE [ModelDifference] ([Oid] char(36) NOT NULL, [UserId] nvarchar(100), [ContextId] nvarchar(100), [Version] int, [OptimisticLockField] int, [GCRecord] int, primary key ([Oid]));
CREATE TABLE [ModelDifferenceAspect] ([Oid] char(36) NOT NULL, [Name] nvarchar(100), [Xml] text, [Owner] char(36), [OptimisticLockField] int, [GCRecord] int, primary key ([Oid]));
CREATE TABLE [Note] ([OID] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, [AddedBy] nvarchar(100), [DateAdded] datetime, [Text] nvarchar(200), [OptimisticLockField] int, [GCRecord] int);
CREATE TABLE [NoteNotes_LoopLoops] ([Loops] int, [Notes] int, [OID] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, [OptimisticLockField] int);
CREATE TABLE [PID] ([OID] int NOT NULL, primary key ([OID]));
CREATE TABLE [PermissionPolicyActionPermissionObject] ([Oid] char(36) NOT NULL, [ActionId] nvarchar(100), [Role] char(36), [OptimisticLockField] int, [GCRecord] int, primary key ([Oid]));
CREATE TABLE [PermissionPolicyMemberPermissionsObject] ([Oid] char(36) NOT NULL, [Members] text, [ReadState] int, [WriteState] int, [Criteria] text, [TypePermissionObject] char(36), [OptimisticLockField] int, [GCRecord] int, primary key ([Oid]));
CREATE TABLE [PermissionPolicyNavigationPermissionsObject] ([Oid] char(36) NOT NULL, [ItemPath] text, [NavigateState] int, [Role] char(36), [OptimisticLockField] int, [GCRecord] int, primary key ([Oid]));
CREATE TABLE [PermissionPolicyObjectPermissionsObject] ([Oid] char(36) NOT NULL, [Criteria] text, [ReadState] int, [WriteState] int, [DeleteState] int, [NavigateState] int, [TypePermissionObject] char(36), [OptimisticLockField] int, [GCRecord] int, primary key ([Oid]));
CREATE TABLE [PermissionPolicyRole] ([Oid] char(36) NOT NULL, [Name] nvarchar(100), [IsAdministrative] bit, [CanEditModel] bit, [PermissionPolicy] int, [OptimisticLockField] int, [GCRecord] int, [ObjectType] int, primary key ([Oid]));
CREATE TABLE [PermissionPolicyTypePermissionsObject] ([Oid] char(36) NOT NULL, [Role] char(36), [TargetType] text, [ReadState] int, [WriteState] int, [CreateState] int, [DeleteState] int, [NavigateState] int, [OptimisticLockField] int, [GCRecord] int, primary key ([Oid]));
CREATE TABLE [PermissionPolicyUser] ([Oid] char(36) NOT NULL, [StoredPassword] text, [ChangePasswordOnFirstLogon] bit, [UserName] nvarchar(100), [IsActive] bit, [OptimisticLockField] int, [GCRecord] int, primary key ([Oid]));
CREATE TABLE [PermissionPolicyUserUsers_PermissionPolicyRoleRoles] ([Roles] char(36), [Users] char(36), [OID] char(36) NOT NULL, [OptimisticLockField] int, primary key ([OID]));
CREATE TABLE [Person] ([Oid] char(36) NOT NULL, [FirstName] nvarchar(100), [LastName] nvarchar(100), [MiddleName] nvarchar(100), [Email] nvarchar(100), [Birthday] datetime, [OptimisticLockField] int, [GCRecord] int, [ObjectType] int, primary key ([Oid]));
CREATE TABLE [ReportDataV2] ([Oid] char(36) NOT NULL, [ObjectTypeName] nvarchar(512), [Content] image, [Name] nvarchar(100), [ParametersObjectTypeName] nvarchar(512), [IsInplaceReport] bit, [PredefinedReportType] nvarchar(512), [OptimisticLockField] int, [GCRecord] int, primary key ([Oid]));
CREATE TABLE [Resource] ([Oid] char(36) NOT NULL, [Caption] nvarchar(100), [Color] int, [OptimisticLockField] int, [GCRecord] int, primary key ([Oid]));
CREATE TABLE [ResourceResources_EventEvents] ([Events] char(36), [Resources] char(36), [OID] char(36) NOT NULL, [OptimisticLockField] int, primary key ([OID]));
CREATE TABLE [Schedule] ([Oid] char(36) NOT NULL, [Name] nvarchar(100), [OptimisticLockField] int, [GCRecord] int, primary key ([Oid]));
CREATE TABLE [XPObjectType] ([OID] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, [TypeName] nvarchar(254), [AssemblyName] nvarchar(254));
CREATE TABLE [XPWeakReference] ([Oid] char(36) NOT NULL, [TargetType] int, [TargetKey] nvarchar(100), [OptimisticLockField] int, [GCRecord] int, [ObjectType] int, primary key ([Oid]));
CREATE UNIQUE INDEX [iAreasLoops_LoopLoops_AreaAreas] on [LoopLoops_AreaAreas]([Areas],[Loops]);
CREATE INDEX [iAreas_LoopLoops_AreaAreas] on [LoopLoops_AreaAreas]([Areas]);
CREATE INDEX [iAssignedTo_DailySchedule] on [DailySchedule]([AssignedTo]);
CREATE INDEX [iAuditedObject_AuditDataItemPersistent] on [AuditDataItemPersistent]([AuditedObject]);
CREATE INDEX [iCompany_Contact] on [Contact]([Company]);
CREATE INDEX [iControlSystem_Instrument] on [Instrument]([ControlSystem]);
CREATE INDEX [iDataSheet_Instrument] on [Instrument]([DataSheet]);
CREATE INDEX [iEndOn_Event] on [Event]([EndOn]);
CREATE INDEX [iEndOn_LoopCheck] on [LoopCheck]([EndOn]);
CREATE UNIQUE INDEX [iEventsResources_ResourceResources_EventEvents] on [ResourceResources_EventEvents]([Events],[Resources]);
CREATE INDEX [iEvents_ResourceResources_EventEvents] on [ResourceResources_EventEvents]([Events]);
CREATE INDEX [iFile_Drawing] on [Drawing]([File]);
CREATE INDEX [iGCRecord_Area] on [Area]([GCRecord]);
CREATE INDEX [iGCRecord_AuditDataItemPersistent] on [AuditDataItemPersistent]([GCRecord]);
CREATE INDEX [iGCRecord_Company] on [Company]([GCRecord]);
CREATE INDEX [iGCRecord_ControlSystem] on [ControlSystem]([GCRecord]);
CREATE INDEX [iGCRecord_ControlSystemType] on [ControlSystemType]([GCRecord]);
CREATE INDEX [iGCRecord_DailySchedule] on [DailySchedule]([GCRecord]);
CREATE INDEX [iGCRecord_Drawing] on [Drawing]([GCRecord]);
CREATE INDEX [iGCRecord_Event] on [Event]([GCRecord]);
CREATE INDEX [iGCRecord_FileData] on [FileData]([GCRecord]);
CREATE INDEX [iGCRecord_FileLinkObject] on [FileLinkObject]([GCRecord]);
CREATE INDEX [iGCRecord_IOType] on [IOType]([GCRecord]);
CREATE INDEX [iGCRecord_Instrument] on [Instrument]([GCRecord]);
CREATE INDEX [iGCRecord_InstrumentType] on [InstrumentType]([GCRecord]);
CREATE INDEX [iGCRecord_JobInfo] on [JobInfo]([GCRecord]);
CREATE INDEX [iGCRecord_JunctionBox] on [JunctionBox]([GCRecord]);
CREATE INDEX [iGCRecord_Loop] on [Loop]([GCRecord]);
CREATE INDEX [iGCRecord_LoopCheck] on [LoopCheck]([GCRecord]);
CREATE INDEX [iGCRecord_LoopCheckStatus] on [LoopCheckStatus]([GCRecord]);
CREATE INDEX [iGCRecord_ModelDifference] on [ModelDifference]([GCRecord]);
CREATE INDEX [iGCRecord_ModelDifferenceAspect] on [ModelDifferenceAspect]([GCRecord]);
CREATE INDEX [iGCRecord_Note] on [Note]([GCRecord]);
CREATE INDEX [iGCRecord_PermissionPolicyActionPermissionObject] on [PermissionPolicyActionPermissionObject]([GCRecord]);
CREATE INDEX [iGCRecord_PermissionPolicyMemberPermissionsObject] on [PermissionPolicyMemberPermissionsObject]([GCRecord]);
CREATE INDEX [iGCRecord_PermissionPolicyNavigationPermissionsObject] on [PermissionPolicyNavigationPermissionsObject]([GCRecord]);
CREATE INDEX [iGCRecord_PermissionPolicyObjectPermissionsObject] on [PermissionPolicyObjectPermissionsObject]([GCRecord]);
CREATE INDEX [iGCRecord_PermissionPolicyRole] on [PermissionPolicyRole]([GCRecord]);
CREATE INDEX [iGCRecord_PermissionPolicyTypePermissionsObject] on [PermissionPolicyTypePermissionsObject]([GCRecord]);
CREATE INDEX [iGCRecord_PermissionPolicyUser] on [PermissionPolicyUser]([GCRecord]);
CREATE INDEX [iGCRecord_Person] on [Person]([GCRecord]);
CREATE INDEX [iGCRecord_ReportDataV2] on [ReportDataV2]([GCRecord]);
CREATE INDEX [iGCRecord_Resource] on [Resource]([GCRecord]);
CREATE INDEX [iGCRecord_Schedule] on [Schedule]([GCRecord]);
CREATE INDEX [iGCRecord_XPWeakReference] on [XPWeakReference]([GCRecord]);
CREATE INDEX [iIOType_Instrument] on [Instrument]([IOType]);
CREATE INDEX [iInstrumentType_Instrument] on [Instrument]([InstrumentType]);
CREATE INDEX [iItem_Event] on [Event]([Item]);
CREATE INDEX [iJunctionBox_Instrument] on [Instrument]([JunctionBox]);
CREATE INDEX [iLocationPlan_Instrument] on [Instrument]([LocationPlan]);
CREATE INDEX [iLoopCheckStatus_Loop] on [Loop]([LoopCheckStatus]);
CREATE INDEX [iLoopDrawing_Instrument] on [Instrument]([LoopDrawing]);
CREATE INDEX [iLoopProvider_Loop] on [Loop]([LoopProvider]);
CREATE INDEX [iLoop_Instrument] on [Instrument]([Loop]);
CREATE UNIQUE INDEX [iLoopsNotes_NoteNotes_LoopLoops] on [NoteNotes_LoopLoops]([Loops],[Notes]);
CREATE INDEX [iLoops_LoopLoops_AreaAreas] on [LoopLoops_AreaAreas]([Loops]);
CREATE INDEX [iLoops_NoteNotes_LoopLoops] on [NoteNotes_LoopLoops]([Loops]);
CREATE INDEX [iModifiedOn_AuditDataItemPersistent] on [AuditDataItemPersistent]([ModifiedOn]);
CREATE INDEX [iNewObject_AuditDataItemPersistent] on [AuditDataItemPersistent]([NewObject]);
CREATE INDEX [iNotes_NoteNotes_LoopLoops] on [NoteNotes_LoopLoops]([Notes]);
CREATE INDEX [iObjectType_Drawing] on [Drawing]([ObjectType]);
CREATE INDEX [iObjectType_Event] on [Event]([ObjectType]);
CREATE INDEX [iObjectType_PermissionPolicyRole] on [PermissionPolicyRole]([ObjectType]);
CREATE INDEX [iObjectType_Person] on [Person]([ObjectType]);
CREATE INDEX [iObjectType_XPWeakReference] on [XPWeakReference]([ObjectType]);
CREATE INDEX [iOldObject_AuditDataItemPersistent] on [AuditDataItemPersistent]([OldObject]);
CREATE INDEX [iOperationType_AuditDataItemPersistent] on [AuditDataItemPersistent]([OperationType]);
CREATE INDEX [iOwner_ModelDifferenceAspect] on [ModelDifferenceAspect]([Owner]);
CREATE INDEX [iPID_Instrument] on [Instrument]([PID]);
CREATE INDEX [iRecurrencePattern_Event] on [Event]([RecurrencePattern]);
CREATE INDEX [iResources_ResourceResources_EventEvents] on [ResourceResources_EventEvents]([Resources]);
CREATE INDEX [iResponsibleCompany_Instrument] on [Instrument]([ResponsibleCompany]);
CREATE INDEX [iRole_PermissionPolicyActionPermissionObject] on [PermissionPolicyActionPermissionObject]([Role]);
CREATE INDEX [iRole_PermissionPolicyNavigationPermissionsObject] on [PermissionPolicyNavigationPermissionsObject]([Role]);
CREATE INDEX [iRole_PermissionPolicyTypePermissionsObject] on [PermissionPolicyTypePermissionsObject]([Role]);
CREATE UNIQUE INDEX [iRolesUsers_PermissionPolicyUserUsers_PermissionPolicyRoleRoles] on [PermissionPolicyUserUsers_PermissionPolicyRoleRoles]([Roles],[Users]);
CREATE INDEX [iRoles_PermissionPolicyUserUsers_PermissionPolicyRoleRoles] on [PermissionPolicyUserUsers_PermissionPolicyRoleRoles]([Roles]);
CREATE INDEX [iSchedule_Event] on [Event]([Schedule]);
CREATE INDEX [iScheduledLoop_DailySchedule] on [DailySchedule]([ScheduledLoop]);
CREATE INDEX [iStartOn_Event] on [Event]([StartOn]);
CREATE INDEX [iStartOn_LoopCheck] on [LoopCheck]([StartOn]);
CREATE INDEX [iTargetTypeTargetKeyGCRecord_XPWeakReference] on [XPWeakReference]([TargetType],[TargetKey],[GCRecord]);
CREATE INDEX [iTargetType_XPWeakReference] on [XPWeakReference]([TargetType]);
CREATE UNIQUE INDEX [iTypeName_XPObjectType] on [XPObjectType]([TypeName]);
CREATE INDEX [iTypePermissionObject_PermissionPolicyMemberPermissionsObject] on [PermissionPolicyMemberPermissionsObject]([TypePermissionObject]);
CREATE INDEX [iTypePermissionObject_PermissionPolicyObjectPermissionsObject] on [PermissionPolicyObjectPermissionsObject]([TypePermissionObject]);
CREATE INDEX [iType_ControlSystem] on [ControlSystem]([Type]);
CREATE INDEX [iUserName_AuditDataItemPersistent] on [AuditDataItemPersistent]([UserName]);
CREATE INDEX [iUsers_PermissionPolicyUserUsers_PermissionPolicyRoleRoles] on [PermissionPolicyUserUsers_PermissionPolicyRoleRoles]([Users]);
COMMIT;
