<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Landrys_Loop_Checkout_System.Module</RootNamespace>
    <AssemblyName>Landrys_Loop_Checkout_System.Module</AssemblyName>
    <Deterministic>false</Deterministic>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Configurations>Debug;Release;EasyTest</Configurations>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'EasyTest'">
    <DefineConstants>$(DefineConstants);EASYTEST</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="**\*.bak" />
    <None Remove="**\*.bak" />
    <EmbeddedResource Remove="**\*.bak" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Model.DesignedDiffs.xafml" />
    <EmbeddedResource Include="Images\**\*.png" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.104.2" />
    <PackageReference Include="DevExpress.ExpressApp" Version="26.1.3" />
    <PackageReference Include="DevExpress.ExpressApp.AuditTrail.Xpo" Version="26.1.3" />
    <PackageReference Include="DevExpress.ExpressApp.Chart" Version="26.1.3" />
    <PackageReference Include="DevExpress.ExpressApp.CodeAnalysis" Version="26.1.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="DevExpress.ExpressApp.ConditionalAppearance" Version="26.1.3" />
    <PackageReference Include="DevExpress.ExpressApp.ReportsV2" Version="26.1.3" />
    <PackageReference Include="DevExpress.ExpressApp.Scheduler" Version="26.1.3" />
    <PackageReference Include="DevExpress.ExpressApp.Security" Version="26.1.3" />
    <PackageReference Include="DevExpress.ExpressApp.Security.Xpo" Version="26.1.3" />
    <PackageReference Include="DevExpress.ExpressApp.Validation" Version="26.1.3" />
    <PackageReference Include="DevExpress.ExpressApp.ViewVariantsModule" Version="26.1.3" />
    <PackageReference Include="DevExpress.ExpressApp.Xpo" Version="26.1.3" />
    <PackageReference Include="DevExpress.Persistent.Base" Version="26.1.3" />
    <PackageReference Include="DevExpress.Persistent.BaseImpl.Xpo" Version="26.1.3" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.15" />
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
  </ItemGroup>
</Project>
