//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Landrys_Loop_Checkout_System.Module.BusinessObjects.Db151516LoopCheckout
{

    public partial class DailySchedule : XPObject
    {
        DateTime fDate;
        public DateTime Date
        {
            get { return fDate; }
            set { SetPropertyValue<DateTime>("Date", ref fDate, value); }
        }
        Loop fScheduledLoop;
        [Association(@"DailyScheduleReferencesLoop")]
        public Loop ScheduledLoop
        {
            get { return fScheduledLoop; }
            set { SetPropertyValue<Loop>("ScheduledLoop", ref fScheduledLoop, value); }
        }
    }

}
