//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Landrys_Loop_Checkout_System.Module.BusinessObjects.Db151516LoopCheckout
{

    public partial class Loop : XPObject
    {
        string fLoopNumber;
        public string LoopNumber
        {
            get { return fLoopNumber; }
            set { SetPropertyValue<string>("LoopNumber", ref fLoopNumber, value); }
        }
        string fDescription;
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        LoopCheckStatus fLoopCheckStatus;
        [Association(@"LoopReferencesLoopCheckStatus")]
        public LoopCheckStatus LoopCheckStatus
        {
            get { return fLoopCheckStatus; }
            set { SetPropertyValue<LoopCheckStatus>("LoopCheckStatus", ref fLoopCheckStatus, value); }
        }
        DateTime fTargetLoopCheckDate;
        public DateTime TargetLoopCheckDate
        {
            get { return fTargetLoopCheckDate; }
            set { SetPropertyValue<DateTime>("TargetLoopCheckDate", ref fTargetLoopCheckDate, value); }
        }
        bool fLoopFolderReceived;
        public bool LoopFolderReceived
        {
            get { return fLoopFolderReceived; }
            set { SetPropertyValue<bool>("LoopFolderReceived", ref fLoopFolderReceived, value); }
        }
        Company fLoopProvider;
        [Association(@"LoopReferencesCompany")]
        [DevExpress.Xpo.DisplayName(@"Company Providing Loop")]
        public Company LoopProvider
        {
            get { return fLoopProvider; }
            set { SetPropertyValue<Company>("LoopProvider", ref fLoopProvider, value); }
        }
        [Association(@"LoopReferencesNote")]
        public XPCollection<Note> Notes { get { return GetCollection<Note>("Notes"); } }
        [Association(@"LoopReferencesArea")]
        public XPCollection<Area> Areas { get { return GetCollection<Area>("Areas"); } }
        [Association(@"DailyScheduleReferencesLoop")]
        public XPCollection<DailySchedule> DailySchedules { get { return GetCollection<DailySchedule>("DailySchedules"); } }
        [Association(@"InstrumentReferencesLoop")]
        public XPCollection<Instrument> Instruments { get { return GetCollection<Instrument>("Instruments"); } }
    }

}
