//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Landrys_Loop_Checkout_System.Module.BusinessObjects.Db151516LoopCheckout
{

    public partial class LoopCheckStatus : XPObject
    {
        string fDescription;
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>("Description", ref fDescription, value); }
        }
        short fSortOrder;
        public short SortOrder
        {
            get { return fSortOrder; }
            set { SetPropertyValue<short>("SortOrder", ref fSortOrder, value); }
        }
        [PersistentAlias("[SortOrder] + '. ' + [Description]")]
        public string DisplayStatus
        {
            get { return (string)(EvaluateAlias("DisplayStatus")); }
        }
        [Association(@"LoopReferencesLoopCheckStatus")]
        public XPCollection<Loop> Loops { get { return GetCollection<Loop>("Loops"); } }
    }

}
