//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Landrys_Loop_Checkout_System.Module.BusinessObjects.Db151516LoopCheckout
{

    public partial class Note : XPObject
    {
        string fText;
        [Size(200)]
        public string Text
        {
            get { return fText; }
            set { SetPropertyValue<string>("Text", ref fText, value); }
        }
        [Association(@"LoopReferencesNote")]
        public XPCollection<Loop> Loops { get { return GetCollection<Loop>("Loops"); } }
    }

}
